diff ./objects/small-0.obj ../server/objects/small-0.obj 
diff ./objects/small-1.obj ../server/objects/small-1.obj 
diff ./objects/small-2.obj ../server/objects/small-2.obj 
diff ./objects/small-3.obj ../server/objects/small-3.obj 
diff ./objects/small-4.obj ../server/objects/small-4.obj 
diff ./objects/small-5.obj ../server/objects/small-5.obj 
diff ./objects/small-6.obj ../server/objects/small-6.obj 
diff ./objects/small-7.obj ../server/objects/small-7.obj 
diff ./objects/small-8.obj ../server/objects/small-8.obj 
diff ./objects/small-9.obj ../server/objects/small-9.obj 
diff ./objects/large-0.obj ../server/objects/large-0.obj 
diff ./objects/large-1.obj ../server/objects/large-1.obj 
diff ./objects/large-2.obj ../server/objects/large-2.obj 
diff ./objects/large-3.obj ../server/objects/large-3.obj 
diff ./objects/large-4.obj ../server/objects/large-4.obj 
diff ./objects/large-5.obj ../server/objects/large-5.obj 
diff ./objects/large-6.obj ../server/objects/large-6.obj 
diff ./objects/large-7.obj ../server/objects/large-7.obj 
diff ./objects/large-8.obj ../server/objects/large-8.obj 
diff ./objects/large-9.obj ../server/objects/large-9.obj 

